name: "NPM Release"
on:
  push:
    branches:
      - main
    paths:
      - 'package/**'
  workflow_dispatch:

jobs:
  npm:
    name: NPM Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - shell: bash
        run: |
          cp './README.md' './package/README.md'
          cp './LICENSE' './package/LICENSE'
      - uses: mikeal/merge-release@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
          DEPLOY_DIR: package
          SRC_PACKAGE_DIR: package