name: "NPM Release"
on:
  push:
    branches:
      - main
    paths:
      - 'package/src/**'
      - 'README.md'
      - 'LICENSE'
  workflow_dispatch:

jobs:
  npm:
    name: NPM Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name : Use Node.js 19.x
        uses : actions/setup-node@v3
        with :
          node-version : 19.x
          cache: npm
      - name: Test & Build
        shell: bash
        run: |
          npm ci
          cd package
          npx vitest run
          npm run build
          cp '../README.md' './README.md'
          cp '../LICENSE' './LICENSE'
      - uses: mikeal/merge-release@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
          DEPLOY_DIR: package
          SRC_PACKAGE_DIR: package